name: DBT Base

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb==1.3.2
          pip install dbt-duckdb
      - name: Run dbt
        run: |
          dbt deps
          dbt build --target prod
        env:
          DBT_PROFILES_DIR: .
          # Ensure MOTHERDUCK_TOKEN is set in your repository secrets or remove the line below if not needed
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      - name: Archive dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts-base
          path: |
            target
            dbt_project.yml
            profiles.yml
