name: Recce PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb==1.3.2 recce
      - name: Download base dbt artifacts
        uses: actions/download-artifact@v2
        with:
          name: dbt-artifacts-base
          path: base
      - name: Run dbt on PR branch
        run: |
          dbt deps
          dbt build --target dev
        env:
          DBT_PROFILES_DIR: .
      - name: Run Recce
        run: |
          recce run --base-path base --github-pull-request-url ${{ github.event.pull_request.html_url }}
        env:
          DBT_PROFILES_DIR: .
      - name: Archive Recce artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recce-artifacts
          path: |
            recce_state.json
